services:
  db:
    image: postgres:15
    container_name: neuroforged-db
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - neuroforged
    labels:
      environment: dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: neuroforged-pgadmin
    restart: always
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - neuroforged
    labels:
      environment: dev

volumes:
  postgres_data:
  pgadmin_data:

networks:
  neuroforged:
