env:
services:
  db:
    image: postgres:15
    restart: always
    container_name: neuroforged-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: neuroforged
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: neuroforged-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@neuroforged.com
      PGADMIN_DEFAULT_PASSWORD: neuroadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
