spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${SPRING_MAIL_SMTP_STARTTLS_ENABLE:true}
      default-encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
calendly:
  client_id: ${CALENDLY_CLIENT_ID}
  redirect-uri: ${CALENDLY_REDIRECT_URI}
  client-secret: ${CALENDLY_CLIENT_SECRET}
  webhook-signing-key: ${CALENDLY_WEBHOOK_SIGNING_KEY}
  scope: organization.read scheduled_events.read scheduled_events.read_all

neuroforged:
  admin:
    email: ${NEUROFORGED_ADMIN_EMAIL}
    password: ${NEUROFORGED_ADMIN_PASSWORD}
  mail:
    from: ${SPRING_MAIL_FROM}
  tokens:
    internal: ${NEUROFORGED_INTERNAL_TOKEN}
