spring:
  mail:
    host: smtp.office365.com
    port: 587
    username: joshua.white@neuroforged.com
    password: fkzltwpfdrhndzyk
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      default-encoding: UTF-8
  datasource:
    url: jdbc:postgresql://localhost:5432/neuroforged
    username: devuser
    password: devpass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
neuroforged:
  tokens:
    internal: secret-test-token-123